version: "3.7"
services:
  # The postgres database.
  postgres:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./.env
    environment:
      # postgres data directory
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/volumes/db/data:/var/lib/postgresql/data
    # uncomment to expose db(postgresql) port to host
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 1s
      timeout: 3s
      retries: 30
  # MinIO server
  minio:
    image: minio/minio:latest
    expose:
      - "9000"
    ports:
      - "9000:9000"
      # MinIO Console is available at http://localhost:9001
      - "9001:9001"
    env_file:
      - ./.env
    volumes:
      - ./docker/volumes/minio/data:/data
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 1s
      timeout: 10s
      retries: 5
    command: server /data --console-address ":9001"
  # Create a bucket named "bucket" if it doesn't exist
  minio-create-bucket:
    image: minio/mc:latest
    env_file:
      - ./.env
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      bash -c "
      mc alias set minio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      if ! mc ls minio | grep --quiet mlflow; then
        mc mb minio/mlflow
      else
        echo 'Bucket mlflow already exists'
      fi
      "
